"""create_chat_tables

Revision ID: e503f4ae17c0
Revises: 
Create Date: 2025-12-09 09:54:33.240638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e503f4ae17c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_threads_updated_at', 'chat_threads', ['updated_at'], unique=False)
    op.create_index('idx_chat_threads_user_updated', 'chat_threads', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_chat_threads_thread_id'), 'chat_threads', ['thread_id'], unique=True)
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'ASSISTANT', name='sender_enum'), nullable=False),
    sa.Column('message_type', sa.Enum('MESSAGE', 'EXPLORER', 'VISUALIZATION', 'STRUCTURED', name='message_type_enum'), nullable=False),
    sa.Column('message_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ERROR', 'TIMEOUT', name='message_status_enum'), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_thread_sender', 'chat_messages', ['thread_id', 'sender', 'timestamp'], unique=False)
    op.create_index('idx_chat_messages_thread_status', 'chat_messages', ['thread_id', 'message_status'], unique=False)
    op.create_index('idx_chat_messages_thread_timestamp', 'chat_messages', ['thread_id', 'timestamp'], unique=False)
    op.create_index('idx_chat_messages_thread_type', 'chat_messages', ['thread_id', 'message_type'], unique=False)
    op.create_index('idx_chat_messages_user_checkpoint', 'chat_messages', ['user_id', 'checkpoint_id'], unique=False)
    op.create_index('idx_chat_messages_user_timestamp', 'chat_messages', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_checkpoint_id'), 'chat_messages', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_message_id'), 'chat_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('message_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_message_id', sa.String(length=255), nullable=False),
    sa.Column('block_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('needs_approval', sa.Boolean(), nullable=False),
    sa.Column('message_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ERROR', 'TIMEOUT', name='message_status_enum'), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.message_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_content_message_created', 'message_content', ['chat_message_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_message_content_block_id'), 'message_content', ['block_id'], unique=True)
    op.create_index(op.f('ix_message_content_chat_message_id'), 'message_content', ['chat_message_id'], unique=False)
    op.create_index(op.f('ix_message_content_type'), 'message_content', ['type'], unique=False)
    # NOTE: Checkpoint tables (checkpoint_writes, checkpoints, checkpoint_blobs, checkpoint_migrations) 
    # are managed by LangGraph and should NOT be modified by Alembic migrations
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Checkpoint tables are managed by LangGraph and should NOT be recreated by Alembic
    op.drop_index(op.f('ix_message_content_type'), table_name='message_content')
    op.drop_index(op.f('ix_message_content_chat_message_id'), table_name='message_content')
    op.drop_index(op.f('ix_message_content_block_id'), table_name='message_content')
    op.drop_index('idx_message_content_message_created', table_name='message_content')
    op.drop_table('message_content')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_checkpoint_id'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_user_timestamp', table_name='chat_messages')
    op.drop_index('idx_chat_messages_user_checkpoint', table_name='chat_messages')
    op.drop_index('idx_chat_messages_thread_type', table_name='chat_messages')
    op.drop_index('idx_chat_messages_thread_timestamp', table_name='chat_messages')
    op.drop_index('idx_chat_messages_thread_status', table_name='chat_messages')
    op.drop_index('idx_chat_messages_thread_sender', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('users')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_thread_id'), table_name='chat_threads')
    op.drop_index('idx_chat_threads_user_updated', table_name='chat_threads')
    op.drop_index('idx_chat_threads_updated_at', table_name='chat_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
